Readme.md
=> fix: Fix broken url in README

radar/methods-and-patterns/monorepo.md
Add monorepo to methods and patterns
=> Add monorepo to methods and patterns

radar/languages-and-frameworks/typescript.md
I think it's worth the effort to be clear on WHY we choose to work in Typescript
website
=> Add Typescript as a language

radar/languages-and-frameworks/typescript.md
=> Fix typos on TypeScript

.github/workflows/main.yml
Add concurrency params to build and deploy action.
=> Add concurrency params to build and deploy action

radar/methods-and-patterns/openapi.md
=> Add OpenAPI

public/config.json, public/messages.json
=> Renamed quadrant Platform and Oparations

radar/platforms-and-services/aws-dynamodb.md, radar/platforms-and-services/aws-ecs.md, radar/platforms-and-services/aws-eventbridge.md, radar/platforms-and-services/aws-lambda.md, radar/platforms-and-services/aws-s3.md
=> Cool aws services

radar/platforms-and-services/azure-function-app.md
=> Azure Function App

radar/platforms-and-services/azure-app-service.md
=> Azure App Service

Readme.md, sheet-template.md
Do you find it useful to have a template to guide the filling the sheet in advance of the PR?
=> Sheet template proposal

radar/languages-and-frameworks/kotlin.md
The goal of this PR is to add Kotlin for backend as trial language.
website
=> feat: add kotlin for backend as trial language

radar/tools/changeset.md
=> Add Changeset to adopt ring

radar/languages-and-frameworks/kotlin-mobile.md, radar/languages-and-frameworks/kotlin.md
=> chore: Add Kotlin for mobile development

radar/tools/create-react-app.md
=> Add Create React App to hold ring

radar/tools/create-react-native-library.md
=> feat: Add create-react-native-library

radar/tools/husky.md
=> chore: Add husky tool

radar/tools/create-react-native-library.md, radar/tools/lint-staged.md
=> chore: Add lint-staged

radar/platforms-and-services/azure-cosmosdb.md
=> Add Cosmos DB to adopt ring

radar/platforms-and-services/azure-api-management.md
=> Add APIM to adopt ring

radar/tools/docker-desktop.md
=> Add Docker Desktop to hold ring

radar/tools/redux.md
=> feat: Add redux framework

radar/tools/flipper.md
=> feat: Add flipper tool

radar/languages-and-frameworks/scala.md
=> Add Scala to hold ring

radar/languages-and-frameworks/gatsbyjs.md
=> Add GatsbyJS to hold ring

radar/tools/vitest.md
=> Add Vitest to adopt ring

radar/tools/prettier.md
=> Add Prettier to adopt ring

radar/tools/dextox.md
=> chore: Add Detox

radar/tools/nvm.md
=> Add nvm to hold ring

radar/platforms-and-services/azure-key-vault.md
=> [EC-202] Add Azure Key Vault as adopt

radar/platforms-and-services/aws-ses.md
=> Add AWS SES

radar/platforms-and-services/azure-container-apps.md
=> add Container Apps

radar/languages-and-frameworks/mutiny.md
=> add java reactive smallrye mutiny

radar/platforms-and-services/azure-notification-hub.md
=> Added Azure Notification Hub

radar/platforms-and-services/azure-notification-hub.md
=> Add infrastructure definition example for Azure Notification Hub

radar/platforms-and-services/azure-ai-search.md
=> [CES-42] - Azure AI Search

radar/platforms-and-services/azure-logic-apps.md
=> [CES-165] Added Azure Logic Apps

radar/tools/optic.md
=> Add Optic to Trial ring

radar/tools/bruno.md
=> New open source client api bruno

radar/tools/husky.md, radar/tools/pre-commit.md
=> Add documentation for pre-commit hooks and enhance Husky usage details

radar/tools/rancher-desktop.md
=> Add Rancher Desktop to the tools section

radar/platforms-and-services/azure-service-bus.md
=> Add Service Bus as assess

radar/platforms-and-services/azure-data-factory.md
=> Add Data Factory to the radar
